### ISSUE TITLE
Add Pre-Pomodoro Hook

### ISSUE THREAD

**Issue by mattmartini** [coddingtonbear/taskwarrior-pomodoro#29]
Could you add a hook to a script that runs at pomodoro start?

I am using TaskWarrior integration for TimeWarrior.  There is an on-modify hook that starts and stops timewarrior every time taskwarrior is started or stopped via cli.  It doesn't work via pomodoro.  

I would like to be able to do the same thing using the taskw-pomo app.  For this I would need a pre-hook to capture the start events.

or you could modify the on-modifiy script to work with taskw-pomo :) 

[on-modify.timewarrior.txt](https://github.com/coddingtonbear/taskwarrior-pomodoro/files/613922/on-modify.timewarrior.txt)

**Comment by coddingtonbear** [comment]
The problem here is that when a subprocess is spawned by a GUI app in OSX, that subprocess does not know the `$PATH` that you have access to in your shell.  Good news, though; that means this is a very easy fix:

1. First, you need to find out where `timew` actually is:  just run `which timew`.
2. Then edit your hook script to replace `timew` within `os.system` requests with the full path that you found in step 1.

I hope this helps; good luck!
