### ISSUE TITLE
Active task is blank

### ISSUE THREAD

**Issue by kmarekspartz** [coddingtonbear/taskwarrior-pomodoro#3]
It says `Active:` but does not show which task is active.

I hope to debug this one too.

**Comment by kmarekspartz** [comment]
This one seems to be due to the json exported for the active task being an array with a object inside it instead of an object on it's own.

**Comment by coddingtonbear** [comment]
Ahh -- this, too, I noticed when trying to run Taskwarrior Pomodoro at work; it should be fixed in the latest version, and was rooted in my not having set a specific configuration option at runtime (specifically [`json.array`](https://github.com/coddingtonbear/taskwarrior-pomodoro/commit/7d9fcde326ca8053a14af36ddbb806a43b076fca); fixed in some changes I pulled in from @Yoi-Nami-Ra's repository).
