### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by kmarekspartz** [coddingtonbear/taskwarrior-pomodoro#4]
Before I get too far with this, can you add a LICENSE file?

**Comment by coddingtonbear** [comment]
Whoops; I had uploaded the standard MIT license [a little later on the same day that you posted this issue](https://github.com/coddingtonbear/taskwarrior-pomodoro/blob/master/LICENSE.txt), but somehow didn't notice this message since I had neglected to have this repository set to "watch".

But, I appreciate your note anyway; when glancing at the license file to reply to this comment, I discovered that I hadn't entered my name!

Cheers!

**Comment by kmarekspartz** [comment]
Thanks!
