### ISSUE TITLE
is this project dead? any alternatives?

### ISSUE THREAD

**Issue by ssbarnea** [coddingtonbear/taskwarrior-pomodoro#40]
Sorry to open a bug for this question but the fact that codebase was not touched in two years and bugs are open without any feedback makes me think that is abandonware.

<img width="430" alt="171106-1024" src="https://user-images.githubusercontent.com/102495/32436697-cc665486-c2dc-11e7-9048-757ff5aa95d5.png">

I hope I am wrong.

**Comment by coddingtonbear** [comment]
Not dead, no -- just rather low on my priority list.  That is not likely to get any better in the future, so I would *love* to see pull requests for things like, for example, updating the project to the latest version of Swift.  If you have the time and experience necessary to do that, please do file a pull request.

Regarding the [single issue that hasn't received feedback (which happens to have submitted by you)](https://github.com/coddingtonbear/taskwarrior-pomodoro/issues/32); I haven't had a chance to look into it because, for complicated reasons, I'm still on El Capitan.  As soon as the stars align in such a way that I have both updated to a modern version of OSX and have the time to spend on this project, I'll have a look.  In the meantime, you may want to try taking a stab at it yourself -- I would love to review and merge a pull request!

Cheers!
